# Generated by Django 3.0.5 on 2020-04-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200426_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='city',
        ),
    ]
