# Generated by Django 3.0.5 on 2020-04-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_remove_vacancy_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.TextField(blank=True, max_length=250, verbose_name='Город'),
        ),
    ]
