# Generated by Django 3.0.5 on 2020-04-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_auto_20200426_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='Speciality',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='speciality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scraping.Speciality', verbose_name='Специальность'),
            preserve_default=False,
        ),
    ]
