# Generated by Django 3.0.5 on 2020-05-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20200426_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок вакансии'),
        ),
    ]
